src/Entity/Client.php
<?php

namespace App\Entity;

use App\Repository\ClientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ClientRepository::class)]
class Client
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $id_client = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $raison_sociale = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $nom_prenom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $adresse = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $code_postal = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $ville = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $telephone = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $mobile = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $email = null;

    /**
     * @var Collection<int, DemandeCommerciale>
     */
    #[ORM\OneToMany(targetEntity: DemandeCommerciale::class, mappedBy: 'client')]
    private Collection $demandeCommerciales;

    public function __construct()
    {
        $this->demandeCommerciales = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdClient(): ?string
    {
        return $this->id_client;
    }

    public function setIdClient(?string $id_client): static
    {
        $this->id_client = $id_client;

        return $this;
    }

    public function getRaisonSociale(): ?string
    {
        return $this->raison_sociale;
    }

    public function setRaisonSociale(?string $raison_sociale): static
    {
        $this->raison_sociale = $raison_sociale;

        return $this;
    }

    public function getNomPrenom(): ?string
    {
        return $this->nom_prenom;
    }

    public function setNomPrenom(?string $nom_prenom): static
    {
        $this->nom_prenom = $nom_prenom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(?string $code_postal): static
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getMobile(): ?string
    {
        return $this->mobile;
    }

    public function setMobile(?string $mobile): static
    {
        $this->mobile = $mobile;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return Collection<int, DemandeCommerciale>
     */
    public function getDemandeCommerciales(): Collection
    {
        return $this->demandeCommerciales;
    }

    public function addDemandeCommerciale(DemandeCommerciale $demandeCommerciale): static
    {
        if (!$this->demandeCommerciales->contains($demandeCommerciale)) {
            $this->demandeCommerciales->add($demandeCommerciale);
            $demandeCommerciale->setClient($this);
        }

        return $this;
    }

    public function removeDemandeCommerciale(DemandeCommerciale $demandeCommerciale): static
    {
        if ($this->demandeCommerciales->removeElement($demandeCommerciale)) {
            // set the owning side to null (unless already changed)
            if ($demandeCommerciale->getClient() === $this) {
                $demandeCommerciale->setClient(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->raison_sociale;
    }
}

src/Entity/Sechoir.php
<?php

namespace App\Entity;

use App\Repository\SechoirRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SechoirRepository::class)]
class Sechoir
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $tremie = null;

    #[ORM\Column(length: 255)]
    private ?string $modele = null;

    #[ORM\Column(length: 255)]
    private ?string $energie = null;

    #[ORM\Column(length: 255)]
    private ?string $charpente = null;

    #[ORM\Column(length: 255)]
    private ?string $acces_exterieur = null;

    #[ORM\Column(length: 255)]
    private ?string $acces_interieur = null;

    #[ORM\Column(length: 255)]
    private ?string $option_volet = null;

    #[ORM\Column(length: 255)]
    private ?string $option_vigi_incendie = null;

    #[ORM\Column(length: 255)]
    private ?string $option_grande_porte = null;

    #[ORM\Column(length: 255)]
    private ?string $option_lot_electrique = null;

    #[ORM\Column(length: 255)]
    private ?string $option_nettoyeur = null;

    #[ORM\Column(length: 255)]
    private ?string $option_filtration = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $type_tampon = null;

    #[ORM\Column(nullable: true)]
    private ?int $diametre_tampon = null;

    #[ORM\Column(nullable: true)]
    private ?int $pente_cone = null;

    #[ORM\Column(nullable: true)]
    private ?int $virole_tampon = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $trappe_sortie = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $type_reprise = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $debit_reprise = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $option_toit = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $sonde_niveau = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $thermometrie = null;

    #[ORM\Column]
    private ?int $quantite = null;

    /**
     * @var Collection<int, DemandeCommerciale>
     */
    #[ORM\OneToMany(targetEntity: DemandeCommerciale::class, mappedBy: 'sechoir')]
    private Collection $demandeCommerciales;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $commentaire = null;

    public function __construct()
    {
        $this->demandeCommerciales = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTremie(): ?string
    {
        return $this->tremie;
    }

    public function setTremie(string $tremie): static
    {
        $this->tremie = $tremie;

        return $this;
    }

    public function getModele(): ?string
    {
        return $this->modele;
    }

    public function setModele(string $modele): static
    {
        $this->modele = $modele;

        return $this;
    }

    public function getEnergie(): ?string
    {
        return $this->energie;
    }

    public function setEnergie(string $energie): static
    {
        $this->energie = $energie;

        return $this;
    }

    public function getCharpente(): ?string
    {
        return $this->charpente;
    }

    public function setCharpente(string $charpente): static
    {
        $this->charpente = $charpente;

        return $this;
    }

    public function getAccesExterieur(): ?string
    {
        return $this->acces_exterieur;
    }

    public function setAccesExterieur(string $acces_exterieur): static
    {
        $this->acces_exterieur = $acces_exterieur;

        return $this;
    }

    public function getAccesInterieur(): ?string
    {
        return $this->acces_interieur;
    }

    public function setAccesInterieur(string $acces_interieur): static
    {
        $this->acces_interieur = $acces_interieur;

        return $this;
    }

    public function getOptionVolet(): ?string
    {
        return $this->option_volet;
    }

    public function setOptionVolet(string $option_volet): static
    {
        $this->option_volet = $option_volet;

        return $this;
    }

    public function getOptionVigiIncendie(): ?string
    {
        return $this->option_vigi_incendie;
    }

    public function setOptionVigiIncendie(string $option_vigi_incendie): static
    {
        $this->option_vigi_incendie = $option_vigi_incendie;

        return $this;
    }

    public function getOptionGrandePorte(): ?string
    {
        return $this->option_grande_porte;
    }

    public function setOptionGrandePorte(string $option_grande_porte): static
    {
        $this->option_grande_porte = $option_grande_porte;

        return $this;
    }

    public function getOptionLotElectrique(): ?string
    {
        return $this->option_lot_electrique;
    }

    public function setOptionLotElectrique(string $option_lot_electrique): static
    {
        $this->option_lot_electrique = $option_lot_electrique;

        return $this;
    }

    public function getOptionNettoyeur(): ?string
    {
        return $this->option_nettoyeur;
    }

    public function setOptionNettoyeur(string $option_nettoyeur): static
    {
        $this->option_nettoyeur = $option_nettoyeur;

        return $this;
    }

    public function getOptionFiltration(): ?string
    {
        return $this->option_filtration;
    }

    public function setOptionFiltration(string $option_filtration): static
    {
        $this->option_filtration = $option_filtration;

        return $this;
    }

    public function getTypeTampon(): ?string
    {
        return $this->type_tampon;
    }

    public function setTypeTampon(?string $type_tampon): static
    {
        $this->type_tampon = $type_tampon;

        return $this;
    }

    public function getDiametreTampon(): ?int
    {
        return $this->diametre_tampon;
    }

    public function setDiametreTampon(?int $diametre_tampon): static
    {
        $this->diametre_tampon = $diametre_tampon;

        return $this;
    }

    public function getPenteCone(): ?int
    {
        return $this->pente_cone;
    }

    public function setPenteCone(?int $pente_cone): static
    {
        $this->pente_cone = $pente_cone;

        return $this;
    }

    public function getViroleTampon(): ?int
    {
        return $this->virole_tampon;
    }

    public function setViroleTampon(?int $virole_tampon): static
    {
        $this->virole_tampon = $virole_tampon;

        return $this;
    }

    public function getTrappeSortie(): ?string
    {
        return $this->trappe_sortie;
    }

    public function setTrappeSortie(?string $trappe_sortie): static
    {
        $this->trappe_sortie = $trappe_sortie;

        return $this;
    }

    public function getTypeReprise(): ?string
    {
        return $this->type_reprise;
    }

    public function setTypeReprise(?string $type_reprise): static
    {
        $this->type_reprise = $type_reprise;

        return $this;
    }

    public function getDebitReprise(): ?string
    {
        return $this->debit_reprise;
    }

    public function setDebitReprise(?string $debit_reprise): static
    {
        $this->debit_reprise = $debit_reprise;

        return $this;
    }

    public function getOptionToit(): ?string
    {
        return $this->option_toit;
    }

    public function setOptionToit(?string $option_toit): static
    {
        $this->option_toit = $option_toit;

        return $this;
    }

    public function getSondeNiveau(): ?string
    {
        return $this->sonde_niveau;
    }

    public function setSondeNiveau(?string $sonde_niveau): static
    {
        $this->sonde_niveau = $sonde_niveau;

        return $this;
    }

    public function getThermometrie(): ?string
    {
        return $this->thermometrie;
    }

    public function setThermometrie(?string $thermometrie): static
    {
        $this->thermometrie = $thermometrie;

        return $this;
    }

    public function getQuantite(): ?int
    {
        return $this->quantite;
    }

    public function setQuantite(int $quantite): static
    {
        $this->quantite = $quantite;

        return $this;
    }

    /**
     * @return Collection<int, DemandeCommerciale>
     */
    public function getDemandeCommerciales(): Collection
    {
        return $this->demandeCommerciales;
    }

    public function addDemandeCommerciale(DemandeCommerciale $demandeCommerciale): static
    {
        if (!$this->demandeCommerciales->contains($demandeCommerciale)) {
            $this->demandeCommerciales->add($demandeCommerciale);
            $demandeCommerciale->setSechoir($this);
        }

        return $this;
    }

    public function removeDemandeCommerciale(DemandeCommerciale $demandeCommerciale): static
    {
        if ($this->demandeCommerciales->removeElement($demandeCommerciale)) {
            // set the owning side to null (unless already changed)
            if ($demandeCommerciale->getSechoir() === $this) {
                $demandeCommerciale->setSechoir(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return (string) $this->id;
    }

    public function getCommentaire(): ?string
    {
        return $this->commentaire;
    }

    public function setCommentaire(?string $commentaire): static
    {
        $this->commentaire = $commentaire;

        return $this;
    }
}

templates/pdf/demande_commerciale.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Demande de Devis</title>
    <style>
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            margin: 0; /* Supprimer la marge par défaut du body */
            padding: 20px; /* Optionnel : ajouter du padding autour du body */
        }

        .header {
            text-align: center; /* Centrer le contenu de l'en-tête */
            margin-bottom: 20px; /* Espacement en bas de l'en-tête */
        }

        .header img {
            max-width: 150px; /* Limiter la taille du logo */
            height: auto; /* Garder les proportions */
        }

        .header h2 {
            margin: 5px 0; /* Espacement autour du titre */
            font-size: 24px; /* Taille du titre */
        }

        .header p {
            margin: 2px 0; /* Espacement autour des paragraphes */
            font-size: 14px; /* Taille des paragraphes */
        }

        .custom-card {
            border: 1px solid #ddd;
            border-radius: 4px;
            overflow: hidden;
            margin-bottom: 20px;
            box-shadow: none; /* Retirer toute ombre de la carte */
        }

        .custom-card-header {
            background-color: #f8f9fa;
            padding: 10px;
            text-align: center; /* Centrer le texte du header */
            margin: 0; /* Enlever les marges */
        }

        .custom-card-header h5 {
            margin: 0; /* Enlever la marge du titre */
            font-size: 18px;
        }

        .custom-card-body {
            padding: 15px;
        }

        .custom-card img {
            width: auto; /* Laisser l'image garder ses proportions */
            height: auto;
            max-width: 80%; /* Limiter la largeur de l'image */
            max-height: 150px; /* Limiter la hauteur de l'image */
            display: block; /* Pour centrer l'image */
            margin: 0 auto; /* Centrer l'image horizontalement */
            box-shadow: none; /* Retirer toute ombre de l'image */
        }

        .highlight-client {
            background-color: #33caff; /* Couleur pour le séparateur */
            width: 1%;
        }

        .highlight-secheuse {
            background-color: #ffdd33; /* Couleur pour le séparateur */
            width: 1%;
        }

        .highlight-options {
            background-color: #0d4efa; /* Couleur pour le séparateur */
            width: 1%;
        }

        .highlight-vis-mobile {
            background-color: #03c80f; /* Couleur pour le séparateur */
            width: 1%;
        }

        .row {
            display: -webkit-box; /* wkhtmltopdf uses this one */
            display: flex;
            -webkit-box-pack: center; /* wkhtmltopdf uses this one */
            justify-content: center;
        }

        .row > div {
            -webkit-box-flex: 1;
            -webkit-flex: 1;
            flex: 1;
            padding: 2px; /* Espacement autour de chaque colonne */
        }

        .col-sm-2 {
            width: 20%; /* 20% pour l'image */
            text-align: center; /* Centrer l'image dans cette colonne */
        }

        .col-sm-1 {
            width: 1%; /* 1% pour la colonne highlight */
        }

        .col-sm-8 {
            width: 80%; /* 70% pour le contenu */
        }

        .card-text strong {
            display: inline; /* S'assurer que le texte est en ligne */
            text-align: justify;
        }

        .col-6 {
            width: 50%; /* Chaque colonne prend 50% de la largeur */
            padding: 10px; /* Espacement autour de chaque colonne, si nécessaire */
        }
    </style>
</head>
<body>

    <!-- En-tête de la demande commerciale -->
    <div class="header">
        <img src="C:\xampp\htdocs\agriconsult\public\imgs\pdf\logo.png" alt="Logo de l'Entreprise">
        <h2>Demande Commerciale</h2>
        <p><strong>Initiales Commerciales :</strong> {{ user.username }}</p>
        <p><strong>N° de Demande :</strong> {{ demandeCommerciale.id }}</p>
        <p><strong>Date :</strong> {{ demandeCommerciale.date|date('d/m/Y') }}</p>
        <p><strong>Type de Demande :</strong> Devis {{ demandeCommerciale.typeDemande }}</p>
        <p><strong>Gamme :</strong> ...</p>
    </div>

    <!-- Preview Client -->
    <div class="custom-card">
        <div class="row">
            <div class="col-sm-2">
                <img src="C:\xampp\htdocs\agriconsult\public\imgs\pdf\picto-client.jpg" class="img-responsive" alt="Client Image">
            </div>
            <div class="col-sm-1 highlight-client"></div>
            <div class="col-sm-8">
                <div class="custom-card-header">
                    <h5 class="card-title">Infos Client</h5>
                </div>
                <div class="custom-card-body">
                    <div class="row">
                        <div class="col-6">
                            <p class="card-text">
                                <strong>ID Client : </strong>{{ client.idClient }}<br>
                                <strong>Raison Sociale : </strong>{{ client.raisonSociale }}<br>
                                <strong>Nom Prénom : </strong>{{ clientData.nomPrenom }}<br>
                                <strong>Adresse : </strong>{{ clientData.adresse }}<br>
                            </p>
                        </div>
                        <div class="col-6">
                            <p class="card-text">
                                <strong>Ville : </strong>{{ clientData.ville }}<br>
                                <strong>Code Postal : </strong>{{ clientData.codePostal }}<br>
                                <strong>Email : </strong>{{ clientData.email }}<br>
                                <strong>Téléphone : </strong>{{ clientData.telephone }}<br>
                                <strong>Mobile : </strong>{{ clientData.mobile }}<br>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

        <!-- Preview Secheuse -->
    <div class="custom-card">
        <div class="row">
            <div class="col-sm-2">
                <img src="C:\xampp\htdocs\agriconsult\public\imgs\pdf\SECHEUSE.jpg" class="img-responsive" alt="Client Image">
            </div>
            <div class="col-sm-1 highlight-secheuse"></div>
            <div class="col-sm-8">
                <div class="custom-card-header">
                    <h5 class="card-title">Infos Sécheuse</h5>
                </div>
                <div class="custom-card-body">
                    <p class="card-text">
                        <strong>Quantite : </strong>{{ secheuse.quantite }}<br>
                        <strong>Type Secheuse : </strong>{{ secheuse.typeSecheuse }}"<br>
                        <strong>Type Plancher : </strong>{{ secheuse.typePlancher }}<br>
                        <strong>Type Reprise : </strong>{{ secheuse.typeReprise }}<br>
                        <strong>Debit Reprise : </strong>{{ secheuse.debitReprise }} T/h<br>
                        <strong>Type Module : </strong>{{ secheuse.typeModule }} CV<br>
                        <strong>Gaz : </strong>{{ secheuse.gaz }}<br>
                        <strong>Biomasse : </strong>{{ secheuse.biomasse }}<br>
                    </p>
                </div>
            </div>
        </div>
    </div>

    {% if options %}
        <!-- Preview Options -->
        <div class="custom-card">
            <div class="row">
                <div class="col-sm-2">
                    <img src="C:\xampp\htdocs\agriconsult\public\imgs\pdf\picto-options.jpg" class="img-responsive" alt="Client Image">
                </div>
                <div class="col-sm-1 highlight-options"></div>
                <div class="col-sm-8">
                    <div class="custom-card-header">
                        <h5 class="card-title">Options</h5>
                    </div>
                    <div class="custom-card-body">
                         <p class="card-text">
                        <strong>Vis Brassage : </strong>{{ secheuse.visBrassage }}<br>
                        <strong>Prenettoyeur : </strong>{{ secheuse.prenettoyeur }}<br>
                        <strong>B2D : </strong>{{ secheuse.b2d }}<br>
                        <strong>Debit Vis : </strong>{{ secheuse.debitVis }}<br>
                    </p>
                </div>
            </div>
        </div>
    </div>
    {% endif %}

    
    {% if visMobile %}
        <!-- Preview Options -->
        <div class="custom-card">
            <div class="row">
                <div class="col-sm-2">
                    <img src="C:\xampp\htdocs\agriconsult\public\imgs\pdf\Vis Mobile.png" class="img-responsive" alt="Client Image">
                </div>
                <div class="col-sm-1 highlight-vis-mobile"></div>
                <div class="col-sm-8">
                    <div class="custom-card-header">
                        <h5 class="card-title">Vis Mobile</h5>
                    </div>
                    <div class="custom-card-body">
                         <p class="card-text">
                        <strong>Vis : </strong>{{ secheuse.visMobile }}<br>
                        <strong>Sortie Orientable : </strong><br>
                        <strong>Bac : </strong><br>
                    </p>
                </div>
            </div>
        </div>
    </div>
    {% endif %}

</body>
</html>